# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf8d0f69e70881e4a769fa3021de10afc158873ada9278bc4d23c08d2b9f9a8dfb3b43ea2dfc470f7f037f511f2b9dd7db69647a4ca087de80769e7b09b0887d

test:
  secret_key_base: 4cdcf9554e1bd09ad00cb4ae32094a374d1afd11660cbc41299a796d074d6fb46b9fadb3cd69bd89077fe3eabbdf5a25ff1c7bce055418d1a731e51fb3dfa470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
